"""Shared, non-interactive scaffolding core for AMAP.

Used by both `amap init` (writes directly to target) and `amap update`
(writes to a staging dir, then syncs). Contains no input() calls.
"""

import shutil
from pathlib import Path
from typing import List, Optional

import yaml

from cli import FRAMEWORK_VERSION
from cli.renderer import render_string
from cli.renderer import _TEXT_EXTENSIONS as _RENDERED_SUFFIXES


# Maps plugin source prefixes to actual directories in the AMAP repo.
SOURCE_MAP = {
    "rules/":               ".amap/rules/",
    "skills/":              ".amap/skills/",
    "workflows/":           ".amap/workflows/",
    "procedures/":          ".amap/procedures/",
    "tools/":               ".amap/tools/",
    "hooks/":               ".amap/hooks/",
    "knowledge-templates/": ".amap/knowledge/templates/",
    "knowledge-active/":    ".amap/knowledge/active/",
    "knowledge-long-term/": ".amap/knowledge/long-term/",
    "meta-prompt.md":       ".amap/meta-prompt.md",
}

# File extensions eligible for single-file Jinja auto-render.
_RENDERABLE_SUFFIXES = {".md", ".yaml", ".yml", ".txt"}


def resolve_source_path(amap_root: Path, source: str) -> Path:
    """Resolve a plugin source path to its actual location in the AMAP repo."""
    for prefix, actual_dir in SOURCE_MAP.items():
        if source.startswith(prefix) or source == prefix.rstrip("/"):
            return amap_root / source.replace(prefix, actual_dir, 1)
    return amap_root / source


def load_manifest(amap_root: Path) -> dict:
    """Load the plugin manifest YAML."""
    with open(amap_root / "cli" / "plugin-manifest.yaml", "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def has_capability(selected_mcps: List[str], mcp_capabilities: dict, required: str) -> bool:
    """True if any selected MCP provides the required capability."""
    return any(
        mcp_capabilities.get(mcp, {}).get("provides") == required
        for mcp in selected_mcps
    )


def get_ownership(plugin: dict) -> str:
    """Return 'framework' (default) or 'user' for a plugin."""
    return plugin.get("ownership", "framework")


def resolved_config_candidates(target: Path) -> List[Path]:
    """Return supported resolved-config locations in preference order."""
    return [
        target / ".agents" / "resolved-config.yaml",
        target / ".claude" / "resolved-config.yaml",
        target / ".amap" / "resolved-config.yaml",
    ]


def generate_resolved_config(
    target_dir: Path, platform, selected_mcps: List[str], language: str
) -> None:
    """Write resolved-config.yaml under the platform's framework root."""
    config_path = target_dir / platform.framework_root / "resolved-config.yaml"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w", encoding="utf-8") as f:
        f.write("# AMAP Resolved Configuration\n")
        f.write("# Generated by: amap init / amap update --reconfigure\n")
        f.write("# The adapter layer is pre-resolved — no runtime lookup needed.\n\n")
        yaml.dump(
            {"resolved": {
                "platform": platform.name,
                "framework_root": platform.framework_root,
                "mcps": selected_mcps,
                "language": language,
                "framework_version": FRAMEWORK_VERSION,
            }},
            f, default_flow_style=False, allow_unicode=True,
        )


def _read_resolved_config(config_path: Path) -> Optional[dict]:
    try:
        with open(config_path, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError:
        return None
    resolved = (data or {}).get("resolved")
    if not isinstance(resolved, dict):
        return None
    return resolved


def load_resolved_config(target: Path) -> Optional[dict]:
    """Load resolved config from native or legacy roots."""
    from cli.platforms import get_platform

    valid = []
    for config_path in resolved_config_candidates(target):
        if not config_path.exists():
            continue
        resolved = _read_resolved_config(config_path)
        if resolved is None:
            continue
        platform_key = resolved.get("platform", "generic")
        try:
            expected_root = get_platform(platform_key).framework_root
        except ValueError:
            expected_root = ".amap"
        resolved.setdefault("framework_root", expected_root)
        resolved["_config_path"] = str(config_path)
        valid.append(resolved)

    if not valid:
        return None

    for resolved in valid:
        path = Path(resolved["_config_path"])
        if path.parent.as_posix().endswith(resolved["framework_root"]):
            return resolved

    return valid[0]


def scaffold_plugin(
    plugin: dict, source_path: Path, target_path: Path, context: dict, jinja_env
) -> dict:
    """Copy or render a single plugin to target_path.

    Returns a stats dict: {"action": "dir"|"rendered"|"copied",
                           "count": int, "rendered": int}.
    Template errors propagate (never swallowed).
    """
    from cli.renderer import copy_and_render_directory

    if plugin.get("copy_dir"):
        count, rendered = copy_and_render_directory(
            jinja_env, source_path, target_path, context
        )
        return {"action": "dir", "count": count, "rendered": rendered}

    target_path.parent.mkdir(parents=True, exist_ok=True)

    if plugin.get("template") or source_path.suffix.lower() in _RENDERABLE_SUFFIXES:
        try:
            content = source_path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            content = None
        if content is not None and ("{{ " in content or plugin.get("template")):
            output = render_string(jinja_env, content, context)
            target_path.write_text(output, encoding="utf-8")
            shutil.copystat(source_path, target_path)
            return {"action": "rendered", "count": 1, "rendered": 1}

    shutil.copy2(source_path, target_path)
    return {"action": "copied", "count": 1, "rendered": 0}


def scaffold_plugins(
    plugins: List[dict], amap_root: Path, write_root: Path, context: dict,
    jinja_env, mcp_capabilities: dict, selected_mcps: List[str],
    only_framework: bool = False, verbose: bool = True,
) -> dict:
    """Process all plugins into write_root.

    only_framework=True skips ownership=='user' plugins (used by update).
    Returns aggregate stats.
    """
    stats = {"rendered": 0, "copied": 0, "dirs": 0, "skipped": 0}
    for plugin in plugins:
        name = plugin["name"]
        requires = plugin.get("requires_capability")
        if requires and not has_capability(selected_mcps, mcp_capabilities, requires):
            if verbose:
                print(f"  ⏭️  {name:35s} (no {requires})")
            stats["skipped"] += 1
            continue
        platform_requires_name = plugin.get("requires_platform")
        platform_name = context.get("platform", {}).get("name")
        if platform_requires_name:
            allowed = (
                platform_requires_name
                if isinstance(platform_requires_name, list)
                else [platform_requires_name]
            )
            if platform_name not in allowed:
                if verbose:
                    print(
                        f"  ⏭️  {name:35s} "
                        f"(platform: {platform_name}, needs: {', '.join(allowed)})"
                    )
                stats["skipped"] += 1
                continue
        platform_requires = plugin.get("requires_platform_capability")
        if platform_requires and not context.get("capabilities", {}).get(platform_requires, False):
            if verbose:
                print(f"  ⏭️  {name:35s} (no platform capability: {platform_requires})")
            stats["skipped"] += 1
            continue
        if only_framework and get_ownership(plugin) == "user":
            if verbose:
                print(f"  🔒 {name:35s} (user-owned, preserved)")
            stats["skipped"] += 1
            continue

        source_path = resolve_source_path(amap_root, plugin["source"])
        output_rel = render_string(jinja_env, plugin["output"], context)
        target_path = write_root / output_rel
        if not source_path.exists():
            if verbose:
                print(f"  ⚠️  {name:35s} (source not found: {source_path})")
            stats["skipped"] += 1
            continue

        result = scaffold_plugin(plugin, source_path, target_path, context, jinja_env)
        if result["action"] == "dir":
            stats["dirs"] += 1
            stats["rendered"] += result["rendered"]
        elif result["action"] == "rendered":
            stats["rendered"] += 1
        else:
            stats["copied"] += 1
        if verbose:
            print(f"  ✅ {output_rel:35s}")
    return stats


def export_as_flat_command(skill_md_text: str) -> str:
    """Render a SKILL.md/workflow file as a frontmatter-free flat command.

    For platforms whose native command format forbids YAML frontmatter
    (e.g. Cursor's .cursor/commands/*.md). pre_conditions are re-rendered
    as a plain markdown checklist so the gates they encode (e.g.
    "ABORT - bootstrap hasn't run") aren't silently dropped.
    """
    _, frontmatter_text, body = skill_md_text.split("---", 2)
    meta = yaml.safe_load(frontmatter_text) or {}
    name = meta.get("name", "")
    description = (meta.get("description") or "").strip()

    header_lines = [f"# {name}", "", f"> {description}"]

    pre_conditions = meta.get("pre_conditions") or []
    if pre_conditions:
        header_lines.append("")
        header_lines.append("## Pre-conditions")
        for cond in pre_conditions:
            target = cond.get("file") or cond.get("input") or ""
            condition = cond.get("condition", "")
            on_fail = cond.get("on_fail", "")
            header_lines.append(f"- `{target}` {condition} -> if not met: {on_fail}")

    return "\n".join(header_lines) + "\n" + body.lstrip("\n")


def scaffold_native_skill_exports(
    plugins: List[dict], write_root: Path, platform, verbose: bool = True,
) -> dict:
    """Mirror skill/workflow plugins into the platform's native skill/command
    location (if it has one), in addition to their .amap/ output.

    Reads from write_root / plugin["output"] — already Jinja-rendered for
    this platform by scaffold_plugins() — rather than from the AMAP repo
    source, so the native export always matches the rendered content
    exactly. No-op if platform.native_skill_export is None.
    """
    stats = {"exported": 0, "skipped": 0}
    export = platform.native_skill_export
    if export is None:
        return stats

    for plugin in plugins:
        if plugin.get("type") not in ("skill", "workflow"):
            continue

        output_path = write_root / plugin["output"]
        source_file = output_path / "SKILL.md" if plugin.get("copy_dir") else output_path
        if not source_file.exists():
            stats["skipped"] += 1
            continue

        text = source_file.read_text(encoding="utf-8")
        if not text.startswith("---"):
            if verbose:
                print(f"  ⏭️  native export skip: {plugin['name']} (no frontmatter)")
            stats["skipped"] += 1
            continue

        name = plugin["name"].removeprefix("workflow-")
        _, frontmatter_text, body = text.split("---", 2)
        meta = yaml.safe_load(frontmatter_text) or {}
        if "name" not in meta:
            meta = {"name": name, **meta}
            frontmatter_text = yaml.dump(meta, default_flow_style=False, allow_unicode=True)
            text = f"---\n{frontmatter_text}---{body}"

        content = export_as_flat_command(text) if export["strip_frontmatter"] else text

        if export["flatten"]:
            target = write_root / export["dir"] / f"{name}.md"
        else:
            target = write_root / export["dir"] / name / "SKILL.md"

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
        stats["exported"] += 1
        if verbose:
            print(f"  ✅ native export: {target.relative_to(write_root)}")

    return stats


def verify_no_unresolved(root: Path) -> List[Path]:
    """Return text files under root that still contain an unresolved '{{ ' marker.

    Scans every extension the renderer actually renders (cli.renderer's
    _TEXT_EXTENSIONS), plus every known platform entry-point filename
    regardless of suffix — `.cursorrules` has an empty suffix and would
    otherwise escape the suffix-only filter, leaving the riskiest file
    (the one this scaffold renames dynamically) unchecked.
    """
    from cli.platforms import PLATFORMS, get_platform

    entry_points = {get_platform(k).config_entry_point for k in PLATFORMS}
    offenders = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in _RENDERED_SUFFIXES and path.name not in entry_points:
            continue
        try:
            if "{{ " in path.read_text(encoding="utf-8"):
                offenders.append(path)
        except UnicodeDecodeError:
            continue
    return offenders


def sync_tree(src: Path, dst: Path) -> int:
    """Copy every file from src over dst (overwrite). Returns file count."""
    count = 0
    for item in src.rglob("*"):
        if not item.is_file():
            continue
        rel = item.relative_to(src)
        target = dst / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(item, target)
        count += 1
    return count
