"""amap init — Scaffold AMAP framework into a target project.

Reads plugin manifest, prompts for platform + MCP selection,
then copies/renders plugins into the target directory.
"""

import os
import shutil
from pathlib import Path
from typing import Dict, List, Optional

import yaml

from cli.platforms import PLATFORMS, get_platform
from cli.renderer import create_renderer, render_file_to_target, copy_and_render_directory


# ─── Source directories mapping ───
# Maps plugin source prefixes to actual directories in the AMAP repo.
# This allows plugins/ manifest to use logical names while the actual
# files live in .agent/ and .knowledge-layer/.
SOURCE_MAP = {
    "rules/":              ".agent/rules/",
    "skills/":             ".agent/skills/",
    "workflows/":          ".agent/workflows/",
    "procedures/":         ".agent/procedures/",
    "tools/":              ".agent/tools/",
    "knowledge-templates/": ".knowledge-layer/templates/",
    "knowledge-active/":   ".knowledge-layer/active/",
    "knowledge-long-term/": ".knowledge-layer/long-term/",
    "AGENTS.md":           "AGENTS.md",
}


def resolve_source_path(amap_root: Path, source: str) -> Path:
    """Resolve a plugin source path to its actual location in the AMAP repo."""
    for prefix, actual_dir in SOURCE_MAP.items():
        if source.startswith(prefix) or source == prefix.rstrip("/"):
            resolved = source.replace(prefix, actual_dir, 1)
            return amap_root / resolved
    # Fallback: treat as relative to amap_root
    return amap_root / source


def load_manifest(amap_root: Path) -> dict:
    """Load the plugin manifest YAML."""
    manifest_path = amap_root / "cli" / "plugin-manifest.yaml"
    with open(manifest_path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def prompt_choice(message: str, choices: List[str], default: int = 0) -> str:
    """Interactive single-choice prompt."""
    print(f"\n{message}")
    for i, choice in enumerate(choices):
        marker = "❯" if i == default else " "
        print(f"  {marker} [{i + 1}] {choice}")

    while True:
        raw = input(f"\nChọn (1-{len(choices)}) [{default + 1}]: ").strip()
        if not raw:
            return choices[default]
        try:
            idx = int(raw) - 1
            if 0 <= idx < len(choices):
                return choices[idx]
        except ValueError:
            pass
        print(f"  ⚠️  Chọn số từ 1 đến {len(choices)}")


def prompt_multi(message: str, choices: List[dict]) -> List[str]:
    """Interactive multi-choice prompt. Each choice has 'key' and 'display'."""
    print(f"\n{message}")
    for i, choice in enumerate(choices):
        print(f"  [{i + 1}] {choice['display']}")

    print(f"\nNhập số thứ tự, cách bởi dấu phẩy (vd: 1,2) hoặc Enter để bỏ qua:")
    raw = input("> ").strip()
    if not raw:
        return []

    selected = []
    for part in raw.split(","):
        try:
            idx = int(part.strip()) - 1
            if 0 <= idx < len(choices):
                selected.append(choices[idx]["key"])
        except ValueError:
            pass
    return selected


def has_capability(selected_mcps: List[str], mcp_capabilities: dict, required: str) -> bool:
    """Check if any selected MCP provides the required capability."""
    for mcp_key in selected_mcps:
        mcp_def = mcp_capabilities.get(mcp_key, {})
        if mcp_def.get("provides") == required:
            return True
    return False





def generate_resolved_config(
    target_dir: Path,
    platform_name: str,
    selected_mcps: List[str],
    language: str,
) -> None:
    """Generate a resolved adapter config (replaces runtime registry.yaml)."""
    config = {
        "# AMAP Resolved Configuration": None,
        "# Generated by: amap init": None,
        "# This file records the platform and MCP choices made at init time.": None,
        "# The adapter layer is pre-resolved — no runtime lookup needed.": None,
        "resolved": {
            "platform": platform_name,
            "mcps": selected_mcps,
            "language": language,
            "framework_version": "3.0",
        },
    }

    config_path = target_dir / ".agent" / "resolved-config.yaml"
    config_path.parent.mkdir(parents=True, exist_ok=True)

    with open(config_path, "w", encoding="utf-8") as f:
        f.write("# AMAP Resolved Configuration\n")
        f.write("# Generated by: amap init\n")
        f.write("# The adapter layer is pre-resolved — no runtime lookup needed.\n\n")
        yaml.dump(
            {
                "resolved": {
                    "platform": platform_name,
                    "mcps": selected_mcps,
                    "language": language,
                    "framework_version": "3.0",
                }
            },
            f,
            default_flow_style=False,
            allow_unicode=True,
        )


def run_init(target_dir: str, amap_root: Optional[str] = None) -> None:
    """Main init command — scaffold AMAP into target project."""

    # Resolve paths
    target = Path(target_dir).resolve()
    if amap_root:
        amap = Path(amap_root).resolve()
    else:
        # Default: CLI lives in <amap_root>/cli/
        amap = Path(__file__).resolve().parent.parent.parent

    # ─── Banner ───
    print()
    print("╔══════════════════════════════════════╗")
    print("║       AMAP Framework v3.0            ║")
    print("║   Agent Memory Architecture Protocol ║")
    print("╚══════════════════════════════════════╝")
    print()
    print(f"  Target: {target}")
    print(f"  Source: {amap}")

    # ─── Load manifest ───
    manifest = load_manifest(amap)
    mcp_capabilities = manifest.get("mcp_capabilities", {})
    languages = manifest.get("languages", ["java", "typescript", "python", "other"])

    # ─── Step 1: Choose platform ───
    platform_choices = [f"{p.display_name}" for p in [get_platform(k) for k in PLATFORMS]]
    platform_keys = list(PLATFORMS.keys())
    chosen_platform_display = prompt_choice("Chọn agent platform:", platform_choices)
    chosen_idx = platform_choices.index(chosen_platform_display)
    chosen_platform_key = platform_keys[chosen_idx]
    platform = get_platform(chosen_platform_key)

    print(f"\n  ✅ Platform: {platform.display_name}")

    # ─── Step 2: Choose MCPs ───
    mcp_choices = [
        {"key": k, "display": v["display"]}
        for k, v in mcp_capabilities.items()
    ]
    selected_mcps = prompt_multi("MCP servers có sẵn:", mcp_choices)

    if selected_mcps:
        print(f"  ✅ MCPs: {', '.join(selected_mcps)}")
    else:
        print("  ℹ️  Không chọn MCP — sẽ dùng file-based tools only")

    # ─── Step 3: Choose language ───
    chosen_language = prompt_choice("Ngôn ngữ chính của project:", languages)
    print(f"  ✅ Language: {chosen_language}")

    # ─── Step 4: Confirm ───
    print(f"\n{'─' * 50}")
    print(f"  Platform:  {platform.display_name}")
    print(f"  MCPs:      {', '.join(selected_mcps) or 'none'}")
    print(f"  Language:  {chosen_language}")
    print(f"  Target:    {target}")
    print(f"{'─' * 50}")

    confirm = input("\nTiến hành scaffold? [Y/n]: ").strip().lower()
    if confirm == "n":
        print("\n❌ Đã huỷ.")
        return

    # ─── Step 5: Build render context ───
    context = platform.build_render_context(selected_mcps, chosen_language)

    # ─── Step 6: Process plugins ───
    print("\nScaffolding AMAP framework...\n")
    plugins = manifest.get("plugins", [])
    jinja_env = create_renderer(str(amap))

    stats = {"copied": 0, "rendered": 0, "skipped": 0, "dirs": 0}

    for plugin in plugins:
        name = plugin["name"]
        source = plugin["source"]
        output = plugin["output"]
        is_template = plugin.get("template", False)
        is_dir = plugin.get("copy_dir", False)
        requires = plugin.get("requires_capability")

        # Check capability requirement
        if requires and not has_capability(selected_mcps, mcp_capabilities, requires):
            print(f"  ⏭️  {name:35s} (no {requires})")
            stats["skipped"] += 1
            continue

        source_path = resolve_source_path(amap, source)
        target_path = target / output

        if not source_path.exists():
            print(f"  ⚠️  {name:35s} (source not found: {source_path})")
            stats["skipped"] += 1
            continue

        if is_dir:
            count, rendered_count = copy_and_render_directory(
                jinja_env, source_path, target_path, context
            )
            if rendered_count > 0:
                print(f"  ✅ {output:35s} ({count} files, {rendered_count} rendered)")
            else:
                print(f"  ✅ {output:35s} ({count} files)")
            stats["dirs"] += 1
            stats["rendered"] += rendered_count
        elif is_template:
            render_file_to_target(jinja_env, str(source_path), context, str(target_path))
            print(f"  ✅ {output:35s} (rendered)")
            stats["rendered"] += 1
        else:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            # Auto-detect Jinja2 variables in single files
            auto_rendered = False
            if source_path.suffix.lower() in {".md", ".yaml", ".yml", ".txt"}:
                try:
                    content = source_path.read_text(encoding="utf-8")
                    if "{{ " in content:
                        from cli.renderer import render_string
                        output_text = render_string(jinja_env, content, context)
                        target_path.write_text(output_text, encoding="utf-8")
                        shutil.copystat(source_path, target_path)
                        auto_rendered = True
                except (UnicodeDecodeError, Exception):
                    pass
            if auto_rendered:
                print(f"  ✅ {output:35s} (rendered)")
                stats["rendered"] += 1
            else:
                shutil.copy2(source_path, target_path)
                print(f"  ✅ {output:35s}")
                stats["copied"] += 1

    # ─── Step 7: Generate resolved config ───
    generate_resolved_config(target, chosen_platform_key, selected_mcps, chosen_language)
    print(f"  ✅ .agent/resolved-config.yaml       (adapter resolved)")

    # ─── Done ───
    total = stats["copied"] + stats["rendered"] + stats["dirs"]
    print(f"\n{'═' * 50}")
    print(f"  Done! AMAP scaffolded for {platform.display_name}")
    print(f"  {total} plugins installed, {stats['skipped']} skipped")
    print(f"{'═' * 50}")
    print(f"\n  Next steps:")
    print(f"  1. Customize .knowledge-layer/long-term/persona.yaml")
    print(f"  2. Run /dna-scan to build author DNA")
    print(f"  3. Run /convention-scan to build conventions")
    print(f"  4. Start your first task: /task <ticket-or-idea>")
    print()
